### ISSUE TITLE
Can't Run Docker Compose

### ISSUE THREAD

**Issue by hxck** [skellgreco/cially#25]
Server: Debian 12
Docker Engine - Community Version: 27.5.1

- Copy&pasted the docker-compose from this Github into Dockge
- Changed the TOKEN and CLIENT_ID variables
- Ran the stack

Everything looks like it spins up fine. I get the create superuser message from Pocketbase, which I can do fine. I can load PB, see the logs, etc. In my Dockge instance I see:

```
cially-bot  | [SUCCESS] The Bot is Running! 
cially-bot  | 
cially-bot  | -----------LOGS------------
cially-bot  | 
cially-bot  | 
cially-bot  | [SUCCESS] The API is running on port: 3001!
```
(Full log is [here](https://pastebin.com/tvuN9Upx).)

When I try to load the website, I get the "Looks like the Discord Bot can't communicate with the Dashboard." error, though no errors show up in my Dockge logs.

The compose shows ```API_URL=http://cially-web:3000/api``` in the ```cially-bot``` environment variables, while the ```cially-web``` environment shows ```BOT_API_URL=http://cially-bot:3001```.

Loading ```http://192.168.50.204:3001/``` gives me ```Cannot GET /```
Loading ```http://192.168.50.204:3000/api``` gives me ```404 | This page could not be found.```

I run Docker on my home server and access things from my main PC via IP (192.168.50.204:3000 etc) but I'm not sure if that has anything to do with it. Any ideas if I mucked something up?

Thanks!

**Comment by skellgreco** [comment]
Hello there!

After reviewing our code, I figured out that we had wrong instructions regarding `API_URL`

Please change the `API_URL` to your bot's URL (example: `http://cially-bot:3001`)

Let me know if it works

Thanks!

**Comment by hxck** [comment]
No dice :(

I changed the ```API_URL``` to ```http://cially-bot:3001``` as indicated in your reply and the updated compose in the repo, restarted the container, and am still getting the same errors.

I removed all related docker volumes and dangling images, made sure no old data existed, and deployed from scratch. Also made sure I cache refreshed my browser. I do see [this error](https://i.imgur.com/G20ntDg.png) in the Pocketbase logs, not sure if it's related.

The only thing that's different with my compose from the repo example is the ```TOKEN``` and ```CLIENT_ID```.

**Comment by skellgreco** [comment]
Hello there! 

There are multiple issues with docker, that we will try to fix in the next major Cially Release (should be this month). 

However, if possible, please help as fixing this faster by providing the following details:
1. Do the data get logged in the pocketbase database when you send a message to your Discord Server?
2. Does changing `http://cially-bot:3001` (and all the other domains of .env) to `http://128.x.x:3001 (your actual IP)` solve the issue?
3. Have you enabled the required intents for your Discord Bot mentioned in the README?
4. Have you applied the pocketbase schema provided?

Please let me know if possible! That will help us debugging the issue easier!

Thanks a lot!

**Comment by hxck** [comment]
1./4. - I did miss uploading the schema, so now that issue is fixed. Sorry about that. I do see all of the proper information in the Pocketbase logs and new messages are being added.
2. No (With this, leaving the compose as ```http://pocketbase:8090``` worked fine after I had provided the schema so inter-network docker communication seems like it's fine.)
3. Yes

Seems like everything is working fine behind the scenes with the Pocketbase instance getting the information like it should, I just can't load the dashboard for some reason.

If there's anything else you can use let me know!

**Comment by skellgreco** [comment]
Hello there!

Could you send me both of your .env (for both, the webserver and the bot)

Really sorry for the inconvenience! I am just not able to reproduce the issue, therefore, your help is really appreciated!

Thanks

**Comment by hxck** [comment]
[This](https://pastebin.com/Tmxx6eLa) is my compose file with the current environment variables.

**Comment by skellgreco** [comment]
Hello there!

I think I've found the issue, and it is related to a bug. 

Last question, are there any errors on Chrome Console while trying to enter the dashboard?

Thanks!

**Comment by hxck** [comment]
Yeah, I'm getting [these errors](https://i.imgur.com/2bFGijn.png) in Brave.

**Comment by skellgreco** [comment]
Alright! 

I just pushed an update on the `main` branch that fixed a couple of issues. 
Also the dashboard will now show the actual error so we can indicate easier the problem!

If possible, please pull the new changes and try again with the same .env

If the error continues, please share a screenshot of the error displayed on the website.

Let's hope it got fixed and it is not a docker issue 🙏🙏

Thanks!

**Comment by hxck** [comment]
Pulled the new update, still isn't loading but the new error shows

```
Error TypeError
TypeError: Failed to parse URL from undefined/fetchGuilds
```

**Comment by skellgreco** [comment]
Oh alright! 

The issue seems to be with how nextjs communicates with the Docker Settings.
I will communicate with the developer that works on Docker and let you know once a fix is applied

Thanks a lot for the feedback!

**Comment by hxck** [comment]
Definitely, thanks for working with me on it!

**Comment by skellgreco** [comment]
Hello everyone!

Sorry for the late support, this was a busy week. After some research, I figured out that making the `BOT_API` variable public might fix the issue. Therefore, I've just pushed the new changes.

Please, if you have time, pull the new changes and rebuild your docker instance. Let me know if the issue is fixed or if the same error (or a different error) appears again on screen.

If possible, go to `http://your-dashboard-url/cially/status` and check if the dashboard communicates with any service at all!

Thanks for your patience!

(@hxck sorry for mentioning you sir, you've just being helping out a lot regarding testing the docker :P. Please give it a go if you have some spare time. Thanks!)

**Comment by hxck** [comment]
Pulled new and restarted. Same error as before on the dashboard:

```
Error TypeError
TypeError: Failed to parse URL from undefined/fetchGuilds
```

Connecting to the status link shows a page, but it's stuck in an infinite load. The ```/settings``` page loads, though. [This](https://i.imgur.com/WHO1kzJ.png) is what the Console shows, and [this](https://i.imgur.com/VjJTxoo.png) is the Network tab.

**Comment by kevinsnijder** [comment]
The output hxck gets is the same I get.

**Comment by skellgreco** [comment]
I honestly struggle with debugging the issue as server side components (such as the API) reads correctly the variables, while the rest of the website does not. 

If anyone has knowledge on docker and nextjs, any contribution would be highly appreciated 

Still investigating from my end...

**Comment by tsvetkovv** [comment]
@skellgreco 

Probably, the issue is here:
https://github.com/skellgreco/cially/blob/315cb5e31db94a6f50374890be97af2a1ce8d886/cially-web/app/cially/status/page.tsx#L19

See example from [the docs](https://nextjs.org/docs/pages/guides/environment-variables#bundling-environment-variables-for-the-browser):

```ts
// This will NOT be inlined, because it uses a variable
const env = process.env
setupAnalyticsService(env.NEXT_PUBLIC_ANALYTICS_ID)
```
 
p.s. here as well
https://github.com/skellgreco/cially/blob/315cb5e31db94a6f50374890be97af2a1ce8d886/cially-web/app/page.tsx#L25

**Comment by skellgreco** [comment]
Hello @tsvetkovv

I am already using `NEXT_PUBLIC` variables. Therefore, what exactly are you suggesting to change?

Thanks

**Comment by tsvetkovv** [comment]
Hello @skellgreco,

Never mind, I was wrong. I investigated a bit further and found this:

> Note: After being built, your app will no longer respond to changes to these environment variables. For instance, if you use a Heroku pipeline to promote slugs built in one environment to another environment, or if you build and deploy a single Docker image to multiple environments, all NEXT_PUBLIC_ variables will be frozen with the value evaluated at build time, so these values need to be set appropriately when the project is built. If you need access to runtime environment values, you'll have to setup your own API to provide them to the client (either on demand or during initialization).

And the article how to make API for this: https://www.vorillaz.com/nextjs-docker-env

P.S. thank you for the project. I tried to run in on my Coolify server via Docker compose, but faced with this issue

**Comment by skellgreco** [comment]
Hello everyone!

I've been trying my best to solve this issue for the past 3-4 days but I've been failing over and over. Due to my lack of knowledge regarding Docker, and as I want to work on new features instead, I am personally stepping out of this issue

If anyone has enough knowledge and time to give it a go, I would be really happy to merge their PR and credit them on the next release! This would help so many people!

I am leaving this open in case someone would like to work on it!

Have a nice day y'all!

**Comment by skellgreco** [comment]
Hello everyone!

I've posted this issue on reddit, and a kind developer sent a bunch of recommendations for this Docker setup which I just implemented!
From my end, it looks like it works. However, I would really appreciate testing these changes on your own and sending some feedback!

Please make sure to pull the new changes!
Thanks y'all

**Comment by hxck** [comment]
1. Removed cially by downing it from Dockge, then running ```docker image prune``` and ```docker volume prune```
2. Ran a fresh ```git clone``` into my stacks folder
3. Copied the new ```docker-compose.yml``` from the respository and re-added my variables for ```token``` and ```client_id```
4. Pulled fresh images and deployed
5. Cache refreshed my browser

Still not working, but this time it just says "fetch failed". The Network tab is clean, but I still see [these errors](https://i.imgur.com/UWD1UIc.png) in the Console tab.

**Comment by skellgreco** [comment]
Alright I believe that I know how to fix this issue.
Have you set up the pocketbase schema as well?

**Comment by hxck** [comment]
[Yep](https://i.imgur.com/B89oqQ4.png)

**Comment by tsvetkovv** [comment]
The same as **hxck**
The issue is that building a Next.js Docker image on CI "bakes in" environment variables available during the `next build`, making the image (ghcr.io/skellgreco/cially-web) environment-specific. 
It tries to fetch GET http://localhost:3000/api/cially/checkStatus, while the website is published on other domain, despite provided NEXT_PUBLIC_WEBSITE_URL

**Comment by skellgreco** [comment]
Hello everyone!

I've pushed new changes regarding this issue. Please pull the new changes and follow the guide below. For me it works like this:
- Clone the project
- Edit the `docker-compose.yaml` file and replace `- NEXT_PUBLIC_WEBSITE_URL=http://...` with the actual URL (instead of localhost or cially-web or anything similar. For example, I was using `- NEXT_PUBLIC_WEBSITE_URL=http://xxxxxxxxx.com` (do not include / in the end)
- Then go to that directory and run `docker compose up --build`

By doing this, everything should work except for the `Messages` tab. I will look at it tomorrow.
Please make sure to setup pocketbase and the other Discord Bot details correctly (token, ID etc). 

Thanks

**Comment by hxck** [comment]
1. Downed the current stack
2. Changed the ```NEXT_PUBLIC_WEBSITE_URL``` variable to ```http://192.168.50.204:3000``` to point at my local server IP
3. Ran ```docker compose up --build``` from the ```cially``` directory
4. [Build process completed](https://i.imgur.com/ilBqebK.png) and deployed the stack
5. Same error as before (fetch failed)

This was just with downing the current stack I had since I just git cloned a couple hours ago, but I can give it another shot tomorrow wiping everything down again with another clean slate.

**Comment by skellgreco** [comment]
Please wipe everything and pull again as I made internal changes as well

Thanks

**Comment by hxck** [comment]
Alright bro, success! After wiping to a fully clean slate, I was able to get it working with a fresh ```git clone``` along with a ```docker compose up --build``` from the command line.

As you've edited in your previous post, the ```Messages``` tab does work, although it looks like if you try to go to the ```Activities``` tab before anything is actually populated you get [this message](https://i.imgur.com/sbrZLAO.png). (At least that's my guess, anyway.)

Props to you for grinding this out. I would poliltely suggest to keep going with it, as the selfhost community has a lot of people who won't do the extra steps, and if they can't just copy&paste the compose they won't use it, which will keep this nifty tool from the more widespread adoption it deserves. For the time being, I would at least outline the procedure we've worked out here in the ```README``` of the repo.

Thanks for working with me, and I'm down to help keep testing in the future!

**Comment by skellgreco** [comment]
Hello!

Glad we managed to make it work after all these tries! I am going to close this issue as the main issue is resolved.

Regarding the setup process, I am planning to create some sort of guide which is going to help the users figure it out easily!

Regarding the activity issue I am aware. If possible, please create an issue about this so I remember to fix it during the week.

I will try to check if it is possible to make the process easier! Again, thanks for helping me out throughout this

## **Solution for anyone having this issue:**
- Clone the project 
- Edit the `docker-compose.yaml` file and replace - `NEXT_PUBLIC_WEBSITE_URL=http://...` with the actual URL (instead of localhost or cially-web or anything similar). For example, I was using - `NEXT_PUBLIC_WEBSITE_URL=http://xxxxxxxxx.com` (do not include / in the end)
- Then go to that directory and run `docker compose up --build`
The issue should be resolved!
